"""initial schema

Revision ID: 001
Revises: 
Create Date: 2026-06-10 08:48:12.226836

"""
from alembic import op
import sqlalchemy as sa


revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('root', sa.String(length=8), nullable=False),
    sa.Column('expiry', sa.Date(), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('right', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_index('ix_instruments_expiry_strike', 'instruments', ['expiry', 'strike'], unique=False)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('api_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_token'),
    sa.UniqueConstraint('name')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('starting_capital', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('delta_hedge_notional', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'season_id', name='uq_accounts_user_season')
    )
    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bid', sa.Float(), nullable=False),
    sa.Column('ask', sa.Float(), nullable=False),
    sa.Column('mid', sa.Float(), nullable=False),
    sa.Column('iv', sa.Float(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('gamma', sa.Float(), nullable=False),
    sa.Column('theta', sa.Float(), nullable=False),
    sa.Column('vega', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('open_interest', sa.Integer(), nullable=False),
    sa.Column('underlying_px', sa.Float(), nullable=False),
    sa.Column('synthetic_quote', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'snapshot_ts', name='uq_snapshots_instrument_ts')
    )
    op.create_index('ix_market_snapshots_ts', 'market_snapshots', ['snapshot_ts'], unique=False)
    op.create_table('pnl_attribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delta_pnl', sa.Float(), nullable=False),
    sa.Column('gamma_pnl', sa.Float(), nullable=False),
    sa.Column('vega_pnl', sa.Float(), nullable=False),
    sa.Column('theta_pnl', sa.Float(), nullable=False),
    sa.Column('vanna_pnl', sa.Float(), nullable=False),
    sa.Column('charm_pnl', sa.Float(), nullable=False),
    sa.Column('volga_pnl', sa.Float(), nullable=False),
    sa.Column('financing_pnl', sa.Float(), nullable=False),
    sa.Column('residual_pnl', sa.Float(), nullable=False),
    sa.Column('total_pnl', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'snapshot_ts', name='uq_attribution_account_ts')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('avg_cost', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'instrument_id', name='uq_positions_account_instrument')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('fill_px', sa.Float(), nullable=False),
    sa.Column('fill_quality', sa.String(length=9), server_default='real', nullable=False),
    sa.Column('traded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trades_account_traded_at', 'trades', ['account_id', 'traded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trades_account_traded_at', table_name='trades')
    op.drop_table('trades')
    op.drop_table('positions')
    op.drop_table('pnl_attribution')
    op.drop_index('ix_market_snapshots_ts', table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_table('accounts')
    op.drop_table('users')
    op.drop_table('seasons')
    op.drop_index('ix_instruments_expiry_strike', table_name='instruments')
    op.drop_table('instruments')
    # ### end Alembic commands ###
